### ISSUE TITLE
[Bug] 버그 제보

### ISSUE THREAD

**Issue by brixxt27** [RollingPaper42/Front-End#162]
# 크롬 피드백
## 로그인
- [x] 간편 로그인에서 버튼의 글자를 클릭할 시 텍스트로 인식 됨
## 스트링캣 만들기
- [ ] 제목 생성 시 개행을 넣는 것이 가능하지 않도록 해야 할 것 같다. 화면 넘어감
## 서랍
- [x] 새로 고침 할 시 내 보드와 보드 그룹이 존재함에도 불구하고 모두 안 보임
## 보드 페이지
- [ ] 새로 고침 시 기본 검은색 화면이 나왔다가 자신이 선택한 테마로 이동함
- [ ] 스크롤시 하이라이트가 되지 않는 점
- [ ] 처음 작성만 했을 때 여기서 하이라이트가 된다는 점을 바로 알 수 없음
- [ ] 눌렀을 때
## 저장 페이지
- [x] 아래 이미지 깨짐
- [x] 기본을 눌렀을 경우 페이지가 깨짐
![image](https://github.com/RollingPaper42/Front-End/assets/83959536/cb7e3189-f5ec-4088-9aad-431537372acf)

- [x] 기본으로 저장 시 넘어가는 부분은 사진에서 짤림
![image](https://github.com/RollingPaper42/Front-End/assets/83959536/db3071c3-c59a-40b8-9223-e6389166f4af)

- [x] 작성자로 저장할 시 From 익명의 스트링캣 사이의 공백이 크게 보임
![image](https://github.com/RollingPaper42/Front-End/assets/83959536/faaed8c3-0b25-4e32-af55-d22b0681931d)

## 그룹 스트링 캣 페이지
- [x] 스트링캣 만들기 버튼이 개행 됨
![image](https://github.com/RollingPaper42/Front-End/assets/83959536/4d08d63f-a492-45f5-b42c-ced95ef16036)

- [x] 보드의 경계가 처음 사용하는 사람으로 잘 보이지 않을 것 같다.
- [x] 컨텐츠 작성 시 완료하지 않은 상태에서 커서를 내리고 구경하다 보면 자신이 작성하던 곳으로 돌아갈 수 없다.

**Comment by lamPolar** [comment]
예전 디자인에 관한 버그여서 이만 closed합니다
